### GET ALL
GET http://localhost:8080/api/v1/articles


### GET One
GET http://localhost:8080/api/v1/articles/

### create
POST http://localhost:8080/api/v1/brands
Content-Type: application/json

{
  "title": "Apple released OS 15 beta",
  "keyword": "apple, os",
  "description": "Today Apple released OS 15 beta",
  "content": "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to fill a space and show the visual elements of a layout or typeface.",
  "date": "2023-10-01"
}